#!/bin/bash
#
# Gets a variable from the tmux environment.

# Copyright (c) 2014 Tobin Van Pelt

vars=$(tmux show-environment)
for line in $vars; do
    if [[ "$line" =~ "$1=" ]]; then
        value=${line##*=}
    fi
done

echo $value
